# Generated by Django 4.0.3 on 2022-04-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='Mensaje', max_length=40),
        ),
    ]
